url: ''

assets:
  compression: false
  digest: false
  source_maps: false
  precompile:
    - '*.map'
  raw:precompile:
    - '*.map'


collections:
  dev_components:
    output: true

include:
  - _dev
