url: ''

assets:
  compression: false

collections:
  dev_components:
    output: true

defaults:
  - scope:
      path: ""
      type: dev_components
    values:
      layout: dev/component
      permalink: /dev/components/:slug

include:
  - _dev
